# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: diegosinpe
# "service" is the name of this project. This will also be added to your AWS resource names.
service: sinpeapi

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

        
functions:
  createContact:
    handler: src/contacts.createContact
    events:
      - httpApi:
          path: /contacts
          method: post

  getContact:
    handler: src/contacts.getContact
    events:
      - httpApi:
          path: /contacts/{phone}
          method: get

  getMovement:
    handler: src/contacts.getMovement
    events:
      - httpApi:
          path: /contacts/movement
          method: get

  sendMoney:
    handler: src/contacts.sendMoney
    events:
      - httpApi:
          path: /contacts/balance
          method: patch

  getMovements:
    handler: src/contacts.getMovements
    events:
      - httpApi:
          path: /contacts/movements/{phone}
          method: get

  getContacts:
    handler: src/contacts.getContacts
    events:
      - httpApi:
          path: /contacts/all/{phone}
          method: get
          
resources:
  Resources:
    Contacts:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Contacts
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: phone
            AttributeType: S
        KeySchema:
          - AttributeName: phone
            KeyType: HASH
